{
 "title": "All Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Host Inbound Traffic [Prometheus]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ryu_byte_count{eth_dst=\"00:00:00:00:00:01\"}[1m]) * 8",
     "legendFormat": "H1"
    },
    {
     "expr": "rate(ryu_byte_count{eth_dst=\"00:00:00:00:00:02\"}[1m]) * 8",
     "legendFormat": "H2"
    },
    {
     "expr": "rate(ryu_byte_count{eth_dst=\"00:00:00:00:00:03\"}[1m]) * 8",
     "legendFormat": "H3"
    },
    {
     "expr": "rate(ryu_byte_count{eth_dst=\"00:00:00:00:00:04\"}[1m]) * 8",
     "legendFormat": "H4"
    },
    {
     "expr": "rate(ryu_byte_count{eth_dst=\"00:00:00:00:00:05\"}[1m]) * 8",
     "legendFormat": "H5"
    },
    {
     "expr": "rate(ryu_byte_count{eth_dst=\"00:00:00:00:00:06\"}[1m]) * 8",
     "legendFormat": "H6"
    }
   ]
  },
  {
   "title": "Spine 11 Port Utilization [Graphite]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(nonNegativeDerivative(summarize(ryu.monitor.11.port.1.tx_bytes, '1min', 'avg', false)), 0.13333), 'P1 Tx')"
    },
    {
     "target": "alias(scale(nonNegativeDerivative(summarize(ryu.monitor.11.port.2.tx_bytes, '1min', 'avg', false)), 0.13333), 'P2 Tx')"
    },
    {
     "target": "alias(scale(nonNegativeDerivative(summarize(ryu.monitor.11.port.3.tx_bytes, '1min', 'avg', false)), 0.13333), 'P3 Tx')"
    },
    {
     "target": "alias(scale(nonNegativeDerivative(summarize(ryu.monitor.11.port.1.rx_bytes, '1min', 'avg', false)), -0.13333), 'P1 Rx')"
    },
    {
     "target": "alias(scale(nonNegativeDerivative(summarize(ryu.monitor.11.port.2.rx_bytes, '1min', 'avg', false)), -0.13333), 'P2 Rx')"
    },
    {
     "target": "alias(scale(nonNegativeDerivative(summarize(ryu.monitor.11.port.3.rx_bytes, '1min', 'avg', false)), -0.13333), 'P3 Rx')"
    }
   ]
  },
  {
   "title": "Spine 12 Port Utilization [InfluxDB]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "P1 Tx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "port_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11' AND \"port_no\"::tag = '1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "datapath::tag", "operator": "=", "value": "12" },
      { "condition": "AND", "key": "port_no::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "P2 Tx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "port_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "datapath::tag", "operator": "=", "value": "12" },
      { "condition": "AND", "key": "port_no::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "P3 Tx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "port_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "datapath::tag", "operator": "=", "value": "12" },
      { "condition": "AND", "key": "port_no::tag", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "P1 Rx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "port_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *(-8)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "datapath::tag", "operator": "=", "value": "12" },
      { "condition": "AND", "key": "port_no::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "P2 Rx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "port_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *(-8)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "datapath::tag", "operator": "=", "value": "12" },
      { "condition": "AND", "key": "port_no::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "P3 Rx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "port_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *(-8)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "datapath::tag", "operator": "=", "value": "12" },
      { "condition": "AND", "key": "port_no::tag", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Flow Count [Prometheus]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ryu_flow_count{datapath_id=\"11\", table_id=\"0\"}",
     "legendFormat": "S11"
    },
    {
     "expr": "ryu_flow_count{datapath_id=\"12\", table_id=\"0\"}",
     "legendFormat": "S12"
    },
    {
     "expr": "sum by(datapath_id) (ryu_flow_count{datapath_id=\"21\"})",
     "legendFormat": "S21"
    },
    {
     "expr": "sum by(datapath_id) (ryu_flow_count{datapath_id=\"22\"})",
     "legendFormat": "S22"
    },
    {
     "expr": "sum by(datapath_id) (ryu_flow_count{datapath_id=\"23\"})",
     "legendFormat": "S23"
    }
   ]
  },
  {
   "title": "Controller Inbound Traffic [InfluxDB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "S11",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "flow_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11' AND \"port_no\"::tag = '1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "datapath::tag", "operator": "=", "value": "11" },
      { "condition": "AND", "key": "dest::tag", "operator": "=", "value": "controller" }
     ]
    },
    {
     "alias": "S12",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "flow_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11' AND \"port_no\"::tag = '1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "datapath::tag", "operator": "=", "value": "12" },
      { "condition": "AND", "key": "dest::tag", "operator": "=", "value": "controller" }
     ]
    },
    {
     "alias": "S21",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "flow_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11' AND \"port_no\"::tag = '1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "datapath::tag", "operator": "=", "value": "21" },
      { "condition": "AND", "key": "dest::tag", "operator": "=", "value": "controller" }
     ]
    },
    {
     "alias": "S22",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "flow_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11' AND \"port_no\"::tag = '1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "datapath::tag", "operator": "=", "value": "22" },
      { "condition": "AND", "key": "dest::tag", "operator": "=", "value": "controller" }
     ]
    },
    {
     "alias": "S23",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "flow_stats",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"), 1s) FROM \"port_stats\" WHERE (\"datapath\"::tag = '11' AND \"port_no\"::tag = '1') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "datapath::tag", "operator": "=", "value": "23" },
      { "condition": "AND", "key": "dest::tag", "operator": "=", "value": "controller" }
     ]
    }
   ]
  }
 ]
}